### PR TITLE
Remove -d flag from dhclient

### PR DESCRIPTION
**Pull request by defect**
Fixing a stupid error I introduced in #32. `-d` will keep dhclient in the foreground.

We want dhclient to go in to the background and manage the interface that gets the first DHCP offer. Using just `-1` will make dhclient try once and exit with code 2 if it fails, otherwise daemonize it self and manage DHCP as usual.

@roymarantz @Primer42 @byxorna

### CODE REVIEW

**Comment by KirilAngov** [comment]
:bullettrain_side: LGTM

**Comment by roymarantz** [comment]
:+1: 
BTW, any idea why -timeout 15 is there?  AFAIK we are in no rush :-)

**Comment by defect** [comment]
At first i thought dhclient would just keep sending DHCPDISCOVERs until it got a reply, but the default timeout seems to be a minute before giving up. I'll get rid of the timeout flag.

**Comment by byxorna** [comment]
lgtm

**Pull request merged**
