### PR TITLE
Docker hub only allows builds from Dockerfiles named "Dockerfile"

### PR DESCRIPTION
**Pull request by Primer42**
I renamed `Dockerfile.centos6` to just `Dockerfile` so we can have automated builds.

@tumblr/systems  @byxorna

### CODE REVIEW

**Comment by roymarantz** [comment]
does this limit us to only building with a single OS?  Not that we have supported that in the past anyway.

**Comment by Primer42** [comment]
You can also let them know here that they should add the feature to support custom Dockerfile names.
https://github.com/docker/hub-feedback/issues/292

**Comment by Primer42** [comment]
@roymarantz we can still build it with multiple OSes. Other projects get around this by having different branches, each with a different flavor of `Dockerfile`. Or we can build and push the centos7 image manually.

**Comment by schallert** [comment]
:+1:

**Comment by roymarantz** [comment]
OK :+1:   we can do the multiple branch hack is/when we need to

**Pull request merged**
